# Generated by Django 4.0.2 on 2022-04-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
