# Generated by Django 4.0.2 on 2022-04-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_userprofile_verified_alter_userverification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
